
; Function declaration
func myFunc(x: int) -> int {
    return x + 1;
}

; hello this is a comment

; Function call
myFunc(1) ? panic('myFunc() throwed an exception')